#http://localhost:8380/swagger-ui/index.html
spring:
  application:
    name: many-to-many
  datasource:
    url: jdbc:postgresql://localhost:5432/many-to-many
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8380